[supabase]
url = "https://ivresluijqsbmylqwolz.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cmVzbHVpanFzYm15bHF3b2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTk1ODMsImV4cCI6MjA2NDAzNTU4M30.hp1ayqfWOtg8XRdbmKMUGpRltoDuSA2-O6mo1SZVYrs"

[postgres]
host = "db.ivresluijqsbmylqwolz.supabase.co"
port = 5432
user = "postgres"
password = "123PRA**!Db"
database = "postgres"

